table:
  name: beneficiary_deployment
  schema: public
object_relationships:
- name: beneficiary
  using:
    foreign_key_constraint_on: beneficiary_id
- name: structure
  using:
    foreign_key_constraint_on: structure_id
