table:
  name: deployment
  schema: public
configuration:
  custom_column_names:
    created_at: createdAt
    updated_at: updatedAt
  custom_root_fields: {}
array_relationships:
  - name: managers
    using:
      foreign_key_constraint_on:
        column: deployment_id
        table:
          name: manager
          schema: public
  - name: structures
    using:
      foreign_key_constraint_on:
        column: deployment_id
        table:
          name: structure
          schema: public
