jobs:
  enabled: true
  runs:
    - name: seed
      needs: [hasura]
      use: SocialGouv/kube-workflow/jobs/seed-db@v1
      with:
        seedPath: hasura/seeds/carnet_de_bord/seed-data.sql

app-backend:
  env:
    - name: APP_URL
      value: https://{{ .Values.global.host }}
    - name: VITE_GRAPHQL_API_URL
      value: https://hasura-{{ .Values.global.host }}/v1/graphql
    - name: SENTRY_ENVIRONMENT
      value: '{{ .Values.global.env }}'
    - name: SENTRY_RELEASE
      value: '{{ .Values.global.branchSlug32 }}'
