ci:
  autoupdate_schedule: quarterly

default_stages: [commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--target-version=py310]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        args: [--config, .prettierrc, --write] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.13.0
    hooks:
      - id: eslint
        types: [file]
        files: \.(svelte|js|ts)$
        args: [-c=.eslintrc.cjs, --ignore-path=.eslintignore, --ignore-pattern=e2e]
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte3
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: 'v8.0.0'
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
