version: '3.8'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=carnet_de_bord
      - POSTGRES_USER=cdb
      - POSTGRES_PASSWORD=test
    ports:
      - '5434:5432'
    volumes:
      - cdb-pgdata:/var/lib/postgresql/data
    restart: always

  graphql-engine:
    image: cdb_hasura
    build:
      context: .
      dockerfile: ./hasura/Dockerfile
    ports:
      - '5000:8080'
    depends_on:
      - 'db'
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: $HASURA_GRAPHQL_DATABASE_URL
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_JWT_SECRET: $HASURA_GRAPHQL_JWT_SECRET
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: admin

volumes:
  cdb-pgdata:
