[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["LionelB <lionel@lumographe.fr>"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
python-dotenv = "^0.20.0"
asyncpg = "^0.25.0"
sentry-sdk = "^1.5.11"
typer = "^0.4.1"
colorama = "^0.4.4"
shellingham = "^1.4.0"
dask = "^2022.4.0"
numpy = "^1.22.3"
pandas = "^1.4.2"
pytest-asyncio = "^0.18.3"
pytest-watch = "^4.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
