global: {}

components:
  app: true
  hasura: true

app:
  probesPath: /healthz
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  containerPort: 80
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap
