app:
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  envFrom:
    - secretRef:
        name: pg-user-{{ .Values.global.branchSlug }}
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap

api:
  envFrom:
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
