
# dont include jobs on deploys
components = ["!jobs", "!_namespace", "*"]
require = ["ts-node/register"]

# dont include underscores-prefix components
[environments.prod]
components = ["!_*", "!apply-seed"]

[environments.dev]
components = ["!apply-seed"]
